### ISSUE TITLE
Running bash commands before/after the microk8s deployment with Openstack provider

### ISSUE THREAD

**Issue by Fevereiro6** [canonical/cluster-api-bootstrap-provider-microk8s#60]
How can we run bash commands before and/or after the microk8s cluster deployment with openstack provider? Preferably using the generated cluster yaml.

**Comment by sachinkumarsingh092** [comment]
In most of the CRDs, the way to run bash commands is by using the below specs:
```
spec:
  command: ["/bin/bash", "-c"]
  args: ["echo 'Hello, World!'"]
  ```
But in our implementations, we haven't had any use-case for this. Can you please elaborate on your use-case for this?
Also, I'm closing the issue: https://github.com/canonical/cluster-api-control-plane-provider-microk8s/issues/34, so as to remove the duplicity of discussion.
